-- The service catalog and studio defaults are created by checked-in migrations.
-- Run `npm run prisma:seed` after a reset to create the local owner, mock staff
-- accounts, and the relational operational fixtures that depend on Auth users.
