"use client";

import Link from "next/link";
import { BarChart3,Bell,CalendarDays,Check,ChevronLeft,ChevronRight,CircleDollarSign,Clock3,Download,LayoutDashboard,Menu,MoreHorizontal,Plus,Search,Settings,ShoppingBag,Sparkles,UserRound,UsersRound,X } from "lucide-react";
import { useEffect,useMemo,useRef,useState } from "react";

type View="Overview"|"Calendar"|"Clients"|"Sales"|"Reports"|"Settings";
type Appointment={id:number;time:string;end:string;name:string;initials:string;service:string;price:string;piercer:string;room:string;status:"Confirmed"|"Requested"|"Completed"|"No-show";color:string};
const appointments:Appointment[]=[
 {id:1,time:"10:00 AM",end:"11:00 AM",name:"Camille Santos",initials:"CS",service:"Double lobe",price:"₱1,600",piercer:"Mika",room:"Station 1",status:"Confirmed",color:"blue"},
 {id:2,time:"11:30 AM",end:"12:15 PM",name:"Paolo Reyes",initials:"PR",service:"Helix",price:"₱1,400",piercer:"Aya",room:"Station 2",status:"Confirmed",color:"violet"},
 {id:3,time:"1:00 PM",end:"2:00 PM",name:"Bea Mendoza",initials:"BM",service:"Navel",price:"₱2,200",piercer:"Jules",room:"Station 3",status:"Requested",color:"amber"},
 {id:4,time:"2:30 PM",end:"3:15 PM",name:"Trina Go",initials:"TG",service:"Conch",price:"₱1,800",piercer:"Mika",room:"Station 1",status:"Confirmed",color:"emerald"},
 {id:5,time:"4:00 PM",end:"4:45 PM",name:"Luis Cruz",initials:"LC",service:"Eyebrow",price:"₱1,500",piercer:"Aya",room:"Station 2",status:"Completed",color:"cyan"},
];
const clients=[["Camille Santos","CS","Active","Aug 12, 2026","Aug 28, 2026","0917 324 1880","₱0"],["Paolo Reyes","PR","New","—","Aug 28, 2026","0998 552 4901","₱400"],["Bea Mendoza","BM","Consent due","Jul 09, 2026","Aug 28, 2026","0916 770 2344","₱0"],["Trina Go","TG","Active","Aug 02, 2026","Sep 14, 2026","0927 115 8930","₱800"],["Luis Cruz","LC","Active","Aug 28, 2026","—","0918 433 1209","₱0"]];
const nav=[[LayoutDashboard,"Overview"],[CalendarDays,"Calendar"],[UsersRound,"Clients"],[ShoppingBag,"Sales"],[BarChart3,"Reports"],[Settings,"Settings"]] as const;
const context:Record<View,{eyebrow:string;title:string;description:string}>={Overview:{eyebrow:"Daily operations",title:"Today",description:"Friday, August 28 · Aura Collective"},Calendar:{eyebrow:"Schedule",title:"August 24–29, 2026",description:"A shared week view for every piercer and station."},Clients:{eyebrow:"Client care",title:"Clients",description:"Bookings, consent forms, procedures, and balances in one record."},Sales:{eyebrow:"Front desk",title:"Sales & payments",description:"Track appointment, walk-in, and product sales."},Reports:{eyebrow:"Performance",title:"Reports",description:"Operational results for August 2026 · Asia/Manila."},Settings:{eyebrow:"Workspace",title:"Studio settings",description:"Manage Aura Collective’s services, people, hours, and booking policy."}};

export function Dashboard(){
 const[active,setActive]=useState<View>("Overview"),[query,setQuery]=useState(""),[menu,setMenu]=useState(false),[modal,setModal]=useState(false),[notice,setNotice]=useState(""),[toastLeaving,setToastLeaving]=useState(false);
 const toastTimers=useRef<number[]>([]);useEffect(()=>()=>toastTimers.current.forEach(window.clearTimeout),[]);
 const page=context[active];const notify=(m:string)=>{toastTimers.current.forEach(window.clearTimeout);setNotice(m);setToastLeaving(false);toastTimers.current=[window.setTimeout(()=>setToastLeaving(true),2300),window.setTimeout(()=>setNotice(""),2700)]};
 const dismissToast=()=>{toastTimers.current.forEach(window.clearTimeout);setToastLeaving(true);toastTimers.current=[window.setTimeout(()=>setNotice(""),400)]};
 const views:Record<View,React.ReactNode>={Overview:<Overview onAdd={()=>setModal(true)} onNavigate={setActive}/>,Calendar:<Calendar onAdd={()=>setModal(true)}/>,Clients:<Clients query={query} setQuery={setQuery}/>,Sales:<Sales onAdd={()=>notify("New sale draft created")}/>,Reports:<Reports onExport={downloadCsv}/>,Settings:<StudioSettings onSave={()=>notify("Studio settings saved")}/>};
 return <div className="ds-app"><aside className={`ds-sidebar ${menu?"open":""}`}><div className="ds-logo"><span><Sparkles/></span><div><strong>lobe</strong><small>STUDIO OS</small></div></div><button className="ds-close" onClick={()=>setMenu(false)} aria-label="Close navigation"><X/></button><p className="ds-nav-label">Workspace</p><nav>{nav.map(([Icon,label])=><button key={label} className={active===label?"active":""} onClick={()=>{setActive(label);setMenu(false)}}><Icon/><span>{label}</span>{label==="Calendar"&&<i>3</i>}</button>)}</nav><div className="ds-account"><span>MS</span><div><strong>Mara Silva</strong><small>Studio owner</small></div><MoreHorizontal/></div></aside>
 <div className="ds-wrap"><section className="ds-canvas"><header className="ds-topbar"><button className="ds-menu" onClick={()=>setMenu(true)} aria-label="Open navigation"><Menu/></button><div className="ds-mobile-logo">lobe</div><div className="ds-page-title"><p>{page.eyebrow}</p><h1>{page.title}</h1><span>{page.description}</span></div><div className="ds-actions"><button className="ds-search" onClick={()=>setActive("Clients")}><Search/><span>Search anything</span><kbd>⌘ K</kbd></button><Link href="/shop/aura-collective/book" className="ds-icon" aria-label="Public booking page"><CalendarDays/></Link><button className="ds-icon" aria-label="Notifications"><Bell/><i/></button><button className="ds-primary" onClick={()=>setModal(true)}><Plus/>New appointment</button></div></header><main className="ds-content">{views[active]}</main></section></div>
 <nav className="ds-bottom">{nav.slice(0,5).map(([Icon,label])=><button key={label} className={active===label?"active":""} onClick={()=>setActive(label)}><Icon/><span>{label}</span></button>)}</nav>{modal&&<AppointmentModal close={()=>setModal(false)} save={()=>{setModal(false);notify("Appointment created")}}/>}{notice&&<button type="button" className={`ds-toast ${toastLeaving?"leaving":""}`} onClick={dismissToast} aria-live="polite" aria-label={`${notice}. Click to dismiss.`}><Check/>{notice}</button>}</div>;
}

function PageHeading({title,description,action}:{title:string;description:string;action?:React.ReactNode}){return <div className="ds-heading"><div><h2>{title}</h2><p>{description}</p></div>{action}</div>}
function Metric({icon,title,value,note,tone}:{icon:React.ReactNode;title:string;value:string;note:string;tone:string}){return <article className="ds-metric"><span className={tone}>{icon}</span><div><small>{title}</small><strong>{value}</strong><p>{note}</p></div></article>}
function Overview({onAdd,onNavigate}:{onAdd:()=>void;onNavigate:(v:View)=>void}){return <div className="ds-view"><PageHeading title="Studio overview" description="A focused look at today’s appointments and studio activity." action={<button className="ds-primary" onClick={onAdd}><Plus/>New appointment</button>}/><section className="ds-metrics"><Metric icon={<CalendarDays/>} title="Appointments" value="8" note="3 remaining today" tone="sky"/><Metric icon={<Clock3/>} title="Booking requests" value="3" note="Waiting for review" tone="amber"/><Metric icon={<CircleDollarSign/>} title="Today’s sales" value="₱12,450" note="18% above last Friday" tone="violet"/><Metric icon={<UserRound/>} title="New clients" value="4" note="18 this month" tone="emerald"/></section><div className="ds-overview-grid"><section className="ds-card"><div className="ds-card-head"><div><h3>Today’s appointments</h3><p>8 scheduled · 10:00 AM–6:00 PM</p></div><button onClick={()=>onNavigate("Calendar")}>View calendar <ChevronRight/></button></div><AppointmentTable rows={appointments}/></section><aside className="ds-stack"><section className="ds-card"><div className="ds-card-head"><div><h3>Booking requests</h3><p>Waiting for review</p></div><span className="ds-count">3</span></div>{[["Nica Villanueva","Nostril · Sep 1","NV"],["Andrea Lim","Flat · Sep 2","AL"],["Sam Flores","Septum · Sep 3","SF"]].map(x=><div className="ds-request" key={x[0]}><span>{x[2]}</span><div><strong>{x[0]}</strong><small>{x[1]}</small></div><button><ChevronRight/></button></div>)}<button className="ds-full" onClick={()=>onNavigate("Calendar")}>Review all requests</button></section><section className="ds-card ds-snapshot"><div className="ds-card-head"><div><h3>August revenue</h3><p>Month to date</p></div><BarChart3/></div><strong>₱186,240</strong><div className="ds-progress"><i/></div><p>74% of ₱250,000 monthly goal <b>+12.4%</b></p></section></aside></div></div>}
function AppointmentTable({rows}:{rows:Appointment[]}){return <div className="ds-table-wrap"><table className="ds-table"><thead><tr><th>Time</th><th>Client & service</th><th>Piercer</th><th>Station</th><th>Status</th><th/></tr></thead><tbody>{rows.map(a=><tr key={a.id}><td><b>{a.time}</b><small>{a.end}</small></td><td><div className="ds-person"><span className={a.color}>{a.initials}</span><div><b>{a.name}</b><small>{a.service} · {a.price}</small></div></div></td><td>{a.piercer}</td><td>{a.room}</td><td><em className={`ds-status ${a.status.toLowerCase().replace("-","")}`}>{a.status}</em></td><td><button className="ds-more"><MoreHorizontal/></button></td></tr>)}</tbody></table></div>}

function Calendar({onAdd}:{onAdd:()=>void}){const days=["MON 24","TUE 25","WED 26","THU 27","FRI 28","SAT 29"];return <div className="ds-view"><PageHeading title="Studio calendar" description="Manage availability, confirmed appointments, and requests." action={<button className="ds-primary" onClick={onAdd}><Plus/>New appointment</button>}/><div className="ds-toolbar"><button className="ds-outline"><ChevronLeft/></button><button className="ds-outline">Today</button><button className="ds-outline"><ChevronRight/></button><select><option>All piercers</option><option>Mika</option><option>Aya</option><option>Jules</option></select><select><option>All stations</option><option>Station 1</option><option>Station 2</option></select><span className="ds-toggle"><b>Week</b><i>Day</i></span></div><section className="ds-card ds-calendar"><div className="ds-calendar-head"><i/>{days.map(d=><div key={d}><span>{d.split(" ")[0]}</span><b>{d.split(" ")[1]}</b></div>)}</div><div className="ds-calendar-body"><div className="ds-times">{["9 AM","10 AM","11 AM","12 PM","1 PM","2 PM","3 PM","4 PM","5 PM"].map(t=><span key={t}>{t}</span>)}</div>{days.map((d,di)=><div className={di===4?"today":""} key={d}>{di===4&&appointments.map((a,i)=><button key={a.id} className={`ds-event ${a.color}`} style={{top:35+i*75}}><b>{a.time} · {a.name}</b><small>{a.service}</small></button>)}{di===2&&<button className="ds-event emerald" style={{top:120}}><b>10:30 AM · Sofia Lee</b><small>Jewelry downsizing</small></button>}</div>)}</div></section></div>}

function Clients({query,setQuery}:{query:string;setQuery:(v:string)=>void}){const shown=useMemo(()=>clients.filter(c=>c.join(" ").toLowerCase().includes(query.toLowerCase())),[query]);return <div className="ds-view"><PageHeading title="Client records" description="Search profiles, forms, appointments, and balances." action={<button className="ds-primary"><Plus/>New client</button>}/><div className="ds-toolbar"><label className="ds-input"><Search/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search name or phone number"/></label><select><option>All clients</option><option>Active</option><option>Consent due</option></select><p>{shown.length} of {clients.length} clients</p></div><section className="ds-card"><div className="ds-table-wrap"><table className="ds-table"><thead><tr><th>Client</th><th>Last / next visit</th><th>Contact</th><th>Balance</th><th/></tr></thead><tbody>{shown.map(c=><tr key={c[0]}><td><div className="ds-person"><span className="blue">{c[1]}</span><div><b>{c[0]}</b><small>{c[2]}</small></div></div></td><td><b>{c[3]}</b><small>Next: {c[4]}</small></td><td><b>{c[5]}</b><small>{c[0].toLowerCase().replace(" ",".")}@email.com</small></td><td><b>{c[6]}</b></td><td><ChevronRight/></td></tr>)}</tbody></table></div><div className="ds-pagination"><span>Showing 1–{shown.length} of {shown.length} clients</span><button>Previous</button><button className="active">1</button><button>Next</button></div></section></div>}

function Sales({onAdd}:{onAdd:()=>void}){const rows=[["#1048","Luis Cruz","Eyebrow piercing","₱1,500","GCash","Completed"],["#1047","Walk-in","Titanium flat-back pair","₱1,200","Cash","Completed"],["#1046","Trina Go","Conch piercing + jewelry","₱2,600","Card","Completed"],["#1045","Paolo Reyes","Helix deposit","₱500","Maya","Partial"],["#1044","Camille Santos","Double lobe","₱1,600","Cash","Completed"]];return <div className="ds-view"><PageHeading title="Sales & payments" description="Today’s appointment, walk-in, and product transactions." action={<button className="ds-primary" onClick={onAdd}><Plus/>New sale</button>}/><section className="ds-metrics three"><Metric icon={<CircleDollarSign/>} title="Gross sales" value="₱12,450" note="7 completed sales" tone="sky"/><Metric icon={<ShoppingBag/>} title="Average sale" value="₱1,779" note="Services and products" tone="violet"/><Metric icon={<Clock3/>} title="Outstanding" value="₱1,300" note="Across 2 clients" tone="amber"/></section><div className="ds-toolbar"><label className="ds-input"><Search/><input placeholder="Search transaction or client"/></label><select><option>All payment methods</option><option>Cash</option><option>GCash</option><option>Card</option></select><input type="date" defaultValue="2026-08-28"/></div><section className="ds-card"><div className="ds-table-wrap"><table className="ds-table"><thead><tr><th>Transaction</th><th>Client</th><th>Items</th><th>Amount</th><th>Payment</th><th>Status</th><th/></tr></thead><tbody>{rows.map(r=><tr key={r[0]}><td><b>{r[0]}</b><small>Aug 28 · 4:20 PM</small></td><td><b>{r[1]}</b></td><td>{r[2]}</td><td><b>{r[3]}</b></td><td>{r[4]}</td><td><em className={`ds-status ${r[5].toLowerCase()}`}>{r[5]}</em></td><td><MoreHorizontal/></td></tr>)}</tbody></table></div></section></div>}

function Reports({onExport}:{onExport:()=>void}){return <div className="ds-view"><PageHeading title="Operational reports" description="Performance summaries for August 1–28, 2026." action={<button className="ds-outline" onClick={onExport}><Download/>Export CSV</button>}/><div className="ds-toolbar"><input type="date" defaultValue="2026-08-01"/><span>to</span><input type="date" defaultValue="2026-08-28"/><select><option>All piercers</option><option>Mika</option><option>Aya</option></select></div><section className="ds-metrics three"><Metric icon={<CircleDollarSign/>} title="Revenue" value="₱186,240" note="+12.4% vs last month" tone="sky"/><Metric icon={<ShoppingBag/>} title="Transactions" value="94" note="₱1,981 average" tone="violet"/><Metric icon={<CalendarDays/>} title="Completed procedures" value="81" note="6 no-shows · 4 cancelled" tone="emerald"/></section><div className="ds-report-grid"><section className="ds-card ds-chart"><div className="ds-card-head"><div><h3>Revenue trend</h3><p>Weekly gross sales</p></div><strong>₱186,240</strong></div><div className="ds-bars">{[48,67,58,82,76,93,72,88].map((h,i)=><div key={i}><i style={{height:`${h}%`}}/><span>W{i+1}</span></div>)}</div></section><section className="ds-card ds-payments"><div className="ds-card-head"><div><h3>Payment methods</h3><p>Collected this period</p></div></div>{[["Cash","₱68,400","37%"],["GCash","₱54,240","29%"],["Card","₱35,800","19%"],["Maya","₱18,600","10%"],["Other","₱9,200","5%"]].map(x=><div key={x[0]}><span>{x[0]}</span><b>{x[1]}</b><small>{x[2]}</small></div>)}</section></div><p className="ds-disclaimer">Operational reports only. Not intended as tax-compliant accounting or official receipts.</p></div>}

function StudioSettings({onSave}:{onSave:()=>void}){return <div className="ds-view"><PageHeading title="Studio settings" description="Changes apply to Aura Collective only." action={<button className="ds-primary" onClick={onSave}><Check/>Save changes</button>}/><div className="ds-settings-grid"><nav className="ds-settings-nav"><button className="active">Studio profile</button><button>Booking policy</button><button>Business hours</button><button>Services & pricing</button><button>Team & roles</button><button>Consent forms</button><button>Notifications</button></nav><section className="ds-card ds-form"><div className="ds-card-head"><div><h3>Studio profile</h3><p>Public identity and contact information.</p></div></div><div className="ds-form-body"><label>Studio name<input defaultValue="Aura Collective"/></label><div><label>Email address<input type="email" defaultValue="hello@auracollective.ph"/></label><label>Phone number<input defaultValue="0917 555 0134"/></label></div><label>Address<textarea defaultValue="5785 Alfonso Street, Poblacion, Makati City"/></label><div><label>Currency<select defaultValue="PHP"><option>PHP</option></select></label><label>Timezone<select defaultValue="Asia/Manila"><option>Asia/Manila</option></select></label></div><label>Public booking URL<input readOnly value="lobe.ph/shop/aura-collective/book"/></label></div></section></div></div>}

function AppointmentModal({close,save}:{close:()=>void;save:()=>void}){return <div className="ds-modal-bg" onMouseDown={close}><div className="ds-modal" onMouseDown={e=>e.stopPropagation()}><div className="ds-modal-head"><div><h2>New appointment</h2><p>Add a confirmed booking or walk-in to the schedule.</p></div><button onClick={close}><X/></button></div><form onSubmit={e=>{e.preventDefault();save()}}><label>Client<input required placeholder="Search or enter client name"/></label><div><label>Service<select defaultValue=""><option value="" disabled>Select service</option><option>Double lobe</option><option>Helix</option><option>Navel</option></select></label><label>Piercer<select><option>Mika</option><option>Aya</option><option>Jules</option></select></label></div><div><label>Date<input type="date" defaultValue="2026-08-28"/></label><label>Start time<input type="time" defaultValue="17:00"/></label></div><footer><button type="button" className="ds-outline" onClick={close}>Cancel</button><button className="ds-primary"><Plus/>Create appointment</button></footer></form></div></div>}
function downloadCsv(){const csv="Date,Transactions,Revenue PHP,Outstanding PHP\n2026-08-28,7,12450,1300";const a=document.createElement("a");a.href=URL.createObjectURL(new Blob([csv],{type:"text/csv"}));a.download="aura-report-2026-08.csv";a.click();URL.revokeObjectURL(a.href)}
