"use client";

import { ChevronLeft, ChevronRight, Clock3, Plus } from "lucide-react";
import { useMemo, useState } from "react";
import { manilaDate, type StudioSettings } from "@/lib/domain";
import type { AvailabilityRecord, ClosureRecord, StaffRecord } from "@/lib/data/staff";
import { Dialog } from "./calendar-workspace";
import { requestWorkspaceRefresh } from "./workspace-refresh";
import { cn } from "@/lib/utils";
import { StudioSelect } from "@/components/ui/studio-select";
import { dashButton, dashError, dashField, operationForm, operationGrid, panelHead, settingSection } from "./dashboard-styles";

const startHour = 8, endHour = 21, hourHeight = 54;
const names = ["SUN", "MON", "TUE", "WED", "THU", "FRI", "SAT"];
type Editor = { kind: "hours" | "availability" | "closure"; id?: string; weekday: number; date: string; start: string; end: string; staffId?: string; reason?: string | null; availabilityDate?: string | null };
const segmented = "grid grid-cols-2 rounded-xl border-[1.5px] border-hippy-ink bg-[#d9ac83] p-[3px] [&>button]:rounded-lg [&>button]:border-0 [&>button]:bg-transparent [&>button]:p-2 [&>button]:font-extrabold";
const segmentedActive = "bg-[#fff4d7]! shadow-[1px_1px_0_#3b2923]";

export function ScheduleSettings({ studio, staff, availability, closures }: { studio: StudioSettings; staff: StaffRecord[]; availability: AvailabilityRecord[]; closures: ClosureRecord[] }) {
  const [anchor, setAnchor] = useState(() => manilaDate(new Date())); const [editor, setEditor] = useState<Editor | null>(null);
  const week = useMemo(() => weekDates(anchor), [anchor]);
  return <section className={settingSection}><div className={panelHead}><div><h3>Hours, availability & closures</h3><p>Staff availability can apply to one date or an inclusive date range. Existing weekly blocks continue to repeat.</p></div><button className={`${dashButton({ variant: "secondary" })} text-[9px]`} onClick={() => setEditor({ kind: "availability", weekday: weekday(anchor), date: anchor, availabilityDate: anchor, start: "10:00", end: "11:00" })}><Plus/> Add schedule block</button></div>
    <div className="flex flex-wrap items-center gap-[7px] border-b border-dashed border-[#c88f6e] bg-[#f4d8a5] px-3.5 py-2.5 [&>span]:rounded-lg [&>span]:border [&>span]:border-l-[5px] [&>span]:border-hippy-ink [&>span]:border-l-[var(--legend,#795d8e)] [&>span]:bg-[#fff7e4] [&>span]:px-2 [&>span]:py-[5px] [&>span]:text-[9px] [&>span]:font-extrabold [&>div]:ml-auto [&>div]:flex [&>div]:gap-1 [&_button]:h-[29px] [&_button]:rounded-[7px] [&_button]:border [&_button]:border-hippy-ink [&_button]:bg-[#fff7e4] [&_button]:px-2 [&_button]:text-[9px] [&_svg]:w-[13px]"><span className="border-l-[#6f927f]!">Studio hours</span>{staff.filter((person) => person.role === "piercer" && person.active).map((person) => <span key={person.id} style={{ "--legend": person.color } as React.CSSProperties}>{person.displayName}</span>)}<span className="border-l-[#b6655d]! bg-[#fbefea]!">Closure</span><div><button aria-label="Previous week" onClick={() => setAnchor(shift(anchor, -7))}><ChevronLeft/></button><button onClick={() => setAnchor(manilaDate(new Date()))}>Today</button><button aria-label="Next week" onClick={() => setAnchor(shift(anchor, 7))}><ChevronRight/></button></div></div>
    <div className="overflow-x-auto [scrollbar-color:#d5aa89_transparent] [scrollbar-width:thin]"><div className="relative grid min-w-[1080px] grid-cols-[64px_repeat(7,minmax(132px,1fr))] grid-rows-[58px_702px] bg-[#fff9eb] max-[760px]:min-w-[982px] max-[760px]:grid-cols-[58px_repeat(7,minmax(132px,1fr))]"><div className="sticky top-0 z-5 flex flex-col items-center justify-center gap-0.5 border-b-[1.5px] border-hippy-ink bg-[#f0d09d] text-[#a24429] [&>svg]:w-4 [&>span]:text-[7px] [&>span]:font-extrabold"><Clock3/><span>GMT+8</span></div>{week.map((date) => { const day = weekday(date); const hours = studio.businessHours[String(day)]; const open = Boolean(hours && !hours.closed); return <div className={cn("sticky top-0 z-5 flex h-[58px] flex-col items-center justify-center border-b-[1.5px] border-l border-dashed border-b-hippy-ink border-l-[#bb7f5d] bg-[#f0d09d]", date === manilaDate(new Date()) && "bg-[#f5dd9d]")} key={date}><div className="flex items-center gap-1 text-[8px] font-[750] text-[#80675d]"><span>{names[day]}</span><strong className="text-[13px] text-hippy-ink">{date.slice(8)}</strong><small>{month(date)}</small></div><button type="button" className={cn("mt-0.5 flex items-center gap-1 rounded-md border border-hippy-ink px-1.5 py-0.5 text-[7px] font-bold", open ? "bg-[#d8e8d3] text-[#315343]" : "bg-[#efb6a6] text-[#783321]")} aria-label={`Edit ${names[day]} studio hours`} onClick={() => setEditor({ kind: "hours", weekday: day, date, start: open ? hours!.open : "10:00", end: open ? hours!.close : "18:00" })}><b>{open ? "Open" : "Closed"}</b><small className="flex gap-1">{open ? <><span>{compactTime(hours!.open)}</span><span>{compactTime(hours!.close)}</span></> : "Set hours"}</small></button></div>; })}
      <div className="relative z-2 border-r-[1.5px] border-hippy-ink bg-[#f7e4bd]">{Array.from({ length: endHour - startHour + 1 }, (_, index) => <span className="absolute right-2.5 translate-y-[5px] text-[8px] font-[650] text-[#8b7166]" key={index} style={{ top: index * hourHeight }}>{hourLabel(startHour + index)}</span>)}</div>
      {week.map((date) => { const day = weekday(date); const hours = studio.businessHours[String(day)]; const dayAvailability = availability.filter((item) => item.availabilityDate ? item.availabilityDate === date : item.weekday === day); const laneIds = staffLaneIds(dayAvailability, staff); const dayClosures = closures.filter((item) => manilaDate(item.startsAt) === date); const fullDayClosed = dayClosures.some((item) => closureCoversOperatingDay(item, hours)); return <div className={cn("relative border-l border-dashed border-[#c79370] bg-[#fff9eb] bg-[repeating-linear-gradient(to_bottom,transparent_0,transparent_53px,#d9b493_54px)]", fullDayClosed && "bg-[#f4d0c7]")} key={date} onDoubleClick={(event) => { const rect = event.currentTarget.getBoundingClientRect(); const minute = Math.max(startHour * 60, Math.min(endHour * 60 - 30, Math.round(((event.clientY - rect.top) / hourHeight * 60 + startHour * 60) / 30) * 30)); setEditor({ kind: "availability", weekday: day, date, availabilityDate: date, start: time(minute), end: time(minute + 60) }); }}>
        {dayAvailability.map((item) => { const person = staff.find((entry) => entry.id === item.staffId); const lane = Math.max(0, laneIds.indexOf(item.staffId)); const label = `${person?.displayName ?? "Staff"}, ${item.startsAt.slice(0,5)} to ${item.endsAt.slice(0,5)}${item.availabilityDate ? ` on ${item.availabilityDate}` : ` every ${names[item.weekday]}`}`; return <button key={item.id} className="absolute left-[calc((100%/var(--schedule-lanes))*var(--schedule-lane)+5px)] z-2 w-[calc(100%/var(--schedule-lanes)-10px)] cursor-pointer overflow-hidden rounded-lg border border-l-[5px] border-hippy-ink border-l-[var(--schedule-color)] bg-[color-mix(in_srgb,var(--schedule-color)_28%,#fff6df)] px-[7px] py-[5px] text-left text-hippy-ink shadow-[1px_2px_0_#3b2923] hover:z-4 hover:-translate-px hover:shadow-[3px_4px_0_#3b2923] [&_strong]:block [&_strong]:overflow-hidden [&_strong]:text-[8px] [&_strong]:text-ellipsis [&_strong]:whitespace-nowrap [&_small]:block [&_small]:overflow-hidden [&_small]:text-[8px] [&_small]:text-ellipsis [&_small]:whitespace-nowrap" style={{ ...blockStyle(item.startsAt, item.endsAt), "--schedule-color": person?.color ?? "#795d8e", "--schedule-lane": lane, "--schedule-lanes": Math.max(1, laneIds.length) } as React.CSSProperties} aria-label={label} title={label} onClick={(event) => { event.stopPropagation(); setEditor({ kind: "availability", id: item.id, weekday: item.weekday, date, availabilityDate: item.availabilityDate, start: item.startsAt.slice(0,5), end: item.endsAt.slice(0,5), staffId: item.staffId }); }} onDoubleClick={(event) => event.stopPropagation()}><strong>{person?.displayName ?? "Staff"}</strong><small>{compactTime(item.startsAt)}–{compactTime(item.endsAt)}{item.availabilityDate ? " · dated" : " · weekly"}</small></button>; })}
        {dayClosures.map((item) => { const fullDay = closureCoversOperatingDay(item, hours); const closureStyle = fullDay ? { top: 0, height: (endHour - startHour) * hourHeight } as React.CSSProperties : blockStyle(manilaTime(item.startsAt), manilaTime(item.endsAt)); return <button key={item.id} className="absolute right-[5px] left-[5px] z-5 cursor-pointer overflow-hidden rounded-lg border border-l-[5px] border-hippy-ink border-l-[#a83930] bg-[repeating-linear-gradient(135deg,#d75d4c_0_7px,#efaa8e_7px_14px)] px-[7px] py-[5px] text-left text-[#301d19] opacity-90 shadow-[1px_2px_0_#3b2923] [&_strong]:block [&_strong]:text-[8px] [&_small]:block [&_small]:text-[8px]" style={closureStyle} aria-label={`Edit closure, ${item.reason || "No reason"}`} onClick={(event) => { event.stopPropagation(); setEditor({ kind: "closure", id: item.id, weekday: day, date, start: manilaTime(item.startsAt), end: manilaTime(item.endsAt), reason: item.reason }); }} onDoubleClick={(event) => event.stopPropagation()}><span><strong>Studio closed</strong><small>{item.reason || "No reason"}</small></span></button>; })}
      </div>; })}
    </div></div><p className="m-0 border-t border-dashed border-[#c88f6e] bg-[#f8e5bd] px-3.5 py-[9px] text-[9px] text-[#78584d]">Double-click an empty time range to add availability. Select any block to edit or delete it.</p>
    {editor && <ScheduleEditor value={editor} staff={staff} onClose={() => setEditor(null)}/>} 
  </section>;
}

function ScheduleEditor({ value, staff, onClose }: { value: Editor; staff: StaffRecord[]; onClose: () => void }) {
  const availableStaff = staff.filter((person) => person.active && person.role === "piercer");
  const initialDate = value.availabilityDate ?? value.date;
  const [kind, setKind] = useState(value.kind); const [dateMode, setDateMode] = useState<"single" | "range">("single"); const [staffId, setStaffId] = useState(value.staffId ?? availableStaff[0]?.id ?? ""); const [dateFrom, setDateFrom] = useState(initialDate); const [dateTo, setDateTo] = useState(initialDate); const [busy, setBusy] = useState(false); const [error, setError] = useState("");
  async function submit(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); setBusy(true); setError(""); const form = new FormData(event.currentTarget); let url = "", method = value.id ? "PATCH" : "POST", payload: Record<string, unknown> = {};
    if (kind === "hours") { url = `/api/settings/business-hours/${value.weekday}`; method = "PATCH"; payload = { open: form.get("start"), close: form.get("end") }; }
    else if (kind === "availability") {
      if (!staffId) { setBusy(false); setError("Choose a staff member."); return; }
      url = value.id ? `/api/availability/${value.id}` : "/api/availability";
      payload = { staffId, startsAt: String(form.get("start") ?? ""), endsAt: String(form.get("end") ?? ""), ...(value.id ? value.availabilityDate ? { availabilityDate: dateFrom } : { weekday: value.weekday } : { dateFrom, dateTo: dateMode === "range" ? dateTo : dateFrom }) };
    }
    else { url = value.id ? `/api/closures/${value.id}` : "/api/closures"; payload = { startsAt: `${form.get("date")}T${form.get("start")}:00+08:00`, endsAt: `${form.get("date")}T${form.get("end")}:00+08:00`, reason: form.get("reason") || null }; }
    const response = await fetch(url, { method, headers: { "content-type": "application/json" }, body: JSON.stringify(payload) }); const body = await response.json(); setBusy(false); if (!response.ok) { setError(firstApiError(body) ?? "Schedule could not be saved."); return; } requestWorkspaceRefresh(); onClose(); }
  async function remove() { setBusy(true); const url = kind === "hours" ? `/api/settings/business-hours/${value.weekday}` : kind === "availability" ? `/api/availability/${value.id}` : `/api/closures/${value.id}`; const response = await fetch(url, { method: "DELETE" }); const body = await response.json(); setBusy(false); if (!response.ok) { setError(body.error?.message ?? "Schedule block could not be deleted."); return; } requestWorkspaceRefresh(); onClose(); }
  return <Dialog title={value.id || kind === "hours" ? "Edit schedule block" : "Add schedule block"} detail={kind === "hours" ? `This changes ${names[value.weekday]} studio hours every week.` : kind === "availability" ? value.id && !value.availabilityDate ? `This is an existing weekly block for every ${names[value.weekday]}.` : "Choose one date or add the same availability across a date range." : "This closure applies only to the selected date."} onClose={onClose}><form className={operationForm} onSubmit={submit}>
    {!value.id && value.kind !== "hours" && <div className={segmented}><button type="button" className={kind === "availability" ? segmentedActive : ""} onClick={() => setKind("availability")}>Staff availability</button><button type="button" className={kind === "closure" ? segmentedActive : ""} onClick={() => setKind("closure")}>Dated closure</button></div>}
    {kind === "availability" && <label className={dashField}>Staff<StudioSelect name="staffId" value={staffId} onValueChange={setStaffId} required ariaLabel="Staff" options={availableStaff.map((person) => ({ value: person.id, label: person.displayName }))} /></label>}
    {kind === "availability" && !value.id && <><div className={segmented}><button type="button" className={dateMode === "single" ? segmentedActive : ""} onClick={() => setDateMode("single")}>Single date</button><button type="button" className={dateMode === "range" ? segmentedActive : ""} onClick={() => { setDateMode("range"); setDateTo((current) => current < dateFrom ? dateFrom : current); }}>Date range</button></div><div className={operationGrid}><label className={dashField}>{dateMode === "range" ? "Starts on" : "Date"}<input name="dateFrom" type="date" value={dateFrom} onChange={(event) => { const next = event.target.value; setDateFrom(next); setDateTo((current) => current < next ? next : current); }} required/></label>{dateMode === "range" && <label className={dashField}>Ends on<input name="dateTo" type="date" value={dateTo} min={dateFrom} onChange={(event) => setDateTo(event.target.value)} required/></label>}</div></>}
    {kind === "availability" && value.id && value.availabilityDate && <label className={dashField}>Date<input name="dateFrom" type="date" value={dateFrom} onChange={(event) => setDateFrom(event.target.value)} required/></label>}
    {kind === "availability" && value.id && !value.availabilityDate && <p className="m-0 rounded-[11px] border border-dashed border-[#ba7652] bg-[#f8dcae] px-3 py-2.5 text-[11px] text-[#60463c]">This legacy block repeats every {names[value.weekday]}. Create a new dated block to limit availability to specific dates.</p>}
    {kind === "closure" && <><label className={dashField}>Date<input name="date" type="date" defaultValue={value.date} required/></label><label className={dashField}>Reason<input name="reason" defaultValue={value.reason ?? ""}/></label></>}
    <div className={operationGrid}><label className={dashField}>Starts<input name="start" type="time" defaultValue={value.start} required/></label><label className={dashField}>Ends<input name="end" type="time" defaultValue={value.end} required/></label></div>
    {error && <p className={dashError} role="alert">{error}</p>}<footer>{(value.id || kind === "hours") && <button type="button" className={`${dashButton({ variant: "primary" })} bg-[#b94735]`} disabled={busy} onClick={() => void remove()}>Delete block</button>}<button type="button" className={dashButton({ variant: "secondary" })} onClick={onClose}>Cancel</button><button className={dashButton({ variant: "primary" })} disabled={busy}>{busy ? "Saving…" : "Save schedule"}</button></footer>
  </form></Dialog>;
}

function blockStyle(start: string, end: string) { const from = minutes(start), to = minutes(end); return { top: Math.max(0,(from-startHour*60)*hourHeight/60), height: Math.max(28,(to-from)*hourHeight/60) } as React.CSSProperties; }
function staffLaneIds(items: AvailabilityRecord[], staff: StaffRecord[]) { const rank = new Map(staff.map((person, index) => [person.id, index])); return [...new Set(items.map((item) => item.staffId))].sort((left, right) => (rank.get(left) ?? Number.MAX_SAFE_INTEGER) - (rank.get(right) ?? Number.MAX_SAFE_INTEGER) || left.localeCompare(right)); }
function closureCoversOperatingDay(item: ClosureRecord, hours: StudioSettings["businessHours"][string] | undefined) { const from = minutes(manilaTime(item.startsAt)), to = minutes(manilaTime(item.endsAt)); const open = hours && !hours.closed ? minutes(hours.open) : startHour * 60; const close = hours && !hours.closed ? minutes(hours.close) : endHour * 60; return from <= open && to >= close; }
function minutes(value: string) { const [h,m] = value.slice(0,5).split(":").map(Number); return h*60+m; }
function time(value: number) { return `${String(Math.floor(value/60)).padStart(2,"0")}:${String(value%60).padStart(2,"0")}`; }
function compactTime(value: string) { const [hour, minute] = value.slice(0,5).split(":").map(Number); return `${hour % 12 || 12}${minute ? `:${String(minute).padStart(2,"0")}` : ""} ${hour < 12 ? "AM" : "PM"}`; }
function weekday(date: string) { return new Date(`${date}T12:00:00Z`).getUTCDay(); }
function shift(date: string, amount: number) { const value = new Date(`${date}T12:00:00Z`); value.setUTCDate(value.getUTCDate()+amount); return value.toISOString().slice(0,10); }
function weekDates(anchor: string) { const first = shift(anchor,-weekday(anchor)); return Array.from({length:7},(_,index)=>shift(first,index)); }
function month(date: string) { return new Intl.DateTimeFormat("en-PH",{month:"short",timeZone:"UTC"}).format(new Date(`${date}T12:00:00Z`)); }
function hourLabel(hour: number) { return new Intl.DateTimeFormat("en-PH",{hour:"numeric",timeZone:"UTC"}).format(new Date(Date.UTC(2020,0,1,hour))); }
function manilaTime(value: string) { return new Intl.DateTimeFormat("en-GB",{hour:"2-digit",minute:"2-digit",hourCycle:"h23",timeZone:"Asia/Manila"}).format(new Date(value)); }
function firstApiError(body: { error?: { message?: string; fields?: Record<string, string[]> } }) { return Object.values(body.error?.fields ?? {}).flat()[0] ?? body.error?.message; }
